const TYPES={
 discovery:{label:'Discovery Call',duration:30,desc:'A focused first conversation to understand the challenge, context and opportunity.'},
 strategy:{label:'Strategy Session',duration:60,desc:'A deeper working session to shape direction, priorities and next moves.'},
 audit:{label:'Digital Audit',duration:45,desc:'Review a digital product, workflow or presence and identify practical improvements.'},
 kickoff:{label:'Project Kickoff',duration:60,desc:'Align on scope, outcomes, roles and the first delivery milestones.'}
};
const state={step:1,type:null,date:null,slot:null,slotsLoadedFor:null,form:{name:'',email:'',company:'',website:'',phone:'',goals:'',projectDetails:'',notes:''},slots:[],loading:false,error:'',booking:null};
const app=document.getElementById('app');
const TZ='Africa/Nairobi';
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(iso,opts={}){return new Intl.DateTimeFormat('en-KE',{timeZone:TZ,dateStyle:'full',timeStyle:'short',...opts}).format(new Date(iso))}
function dateOnly(d){return d.toLocaleDateString('en-CA',{timeZone:TZ})}
function updateProgress(){document.querySelectorAll('.progress-labels span').forEach(x=>x.classList.toggle('active',Number(x.dataset.p)===state.step));document.getElementById('progress-fill').style.width=`${state.step*25}%`}
function saveForm(){['name','email','company','website','phone','goals','projectDetails','notes'].forEach(k=>{const el=document.getElementById('f-'+k);if(el)state.form[k]=el.value})}
function setStep(n){saveForm();state.step=n;state.error='';render()}
function render(){updateProgress(); if(state.booking)return renderSuccess(); if(state.step===1)return renderTypes(); if(state.step===2)return renderCalendar(); if(state.step===3)return renderDetails(); return renderConfirm();}
function renderTypes(){app.innerHTML=`<div class="content"><div class="kicker">01 · Choose a session</div><h2 class="title">What would be most useful?</h2><p class="sub">Pick the format that matches where you are. You can change this before confirming.</p><div class="grid">${Object.entries(TYPES).map(([key,t])=>`<button class="type ${state.type===key?'selected':''}" data-type="${key}"><span class="check">✓</span><h3>${t.label}</h3><p>${t.desc}</p><span class="duration">${t.duration} min · Google Meet</span></button>`).join('')}</div><div class="actions"><span></span><button class="btn primary" id="next-type" ${state.type?'':'disabled'}>Continue →</button></div></div>`;document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{state.type=b.dataset.type;render()});document.getElementById('next-type').onclick=()=>setStep(2)}
function upcomingDates(){const out=[];let d=new Date();for(let i=0;out.length<14&&i<30;i++){const x=new Date(d);x.setDate(d.getDate()+i);const day=x.getDay();if(day!==0&&day!==6)out.push(x)}return out}
async function loadSlots(){if(!state.date||!state.type)return;state.loading=true;state.error='';state.slotsLoadedFor=`${state.date}:${state.type}`;render();try{const r=await fetch(`/api/bookings/availability?date=${state.date}&duration=${TYPES[state.type].duration}`);const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not load availability');state.slots=j.slots||[]}catch(e){state.error=e.message;state.slots=[]}finally{state.loading=false;render()}}
function renderCalendar(){const dates=upcomingDates();if(!state.date)state.date=dateOnly(dates[0]);const chosen=new Date(`${state.date}T00:00:00+03:00`);app.innerHTML=`<div class="content"><div class="kicker">02 · Find a time</div><h2 class="title">Make space for the conversation.</h2><p class="sub">${TYPES[state.type].label} · ${TYPES[state.type].duration} minutes. Your Google Calendar is checked before slots are shown.</p><div class="days">${dates.map(d=>{const iso=dateOnly(d);return `<button class="day ${iso===state.date?'selected':''}" data-date="${iso}"><span class="dow">${d.toLocaleDateString('en-US',{weekday:'short'})}</span><span class="num">${d.toLocaleDateString('en-US',{day:'numeric'})}</span></button>`}).join('')}</div><div class="slot-head"><strong>${chosen.toLocaleDateString('en-KE',{weekday:'long',month:'long',day:'numeric'})}</strong><span>Times are EAT</span></div>${state.loading?`<div class="loading"><div class="spinner"></div>Checking your calendar…</div>`:`<div class="slots">${state.slots.length?state.slots.map(s=>`<button class="slot ${state.slot===s.time?'selected':''}" data-slot="${s.time}">${esc(s.label)}</button>`).join(''):`<div class="notice" style="grid-column:1/-1">No open slots for this date. Try another day.</div>`}</div>`}${state.error?`<div class="error">${esc(state.error)}</div>`:''}<div class="actions"><button class="btn ghost" id="back-type">← Back</button><button class="btn primary" id="next-time" ${state.slot?'':'disabled'}>Continue →</button></div></div>`;document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{state.date=b.dataset.date;state.slot=null;state.slotsLoadedFor=null;loadSlots()});document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{state.slot=b.dataset.slot;render()});document.getElementById('back-type').onclick=()=>setStep(1);document.getElementById('next-time').onclick=()=>setStep(3);if(!state.loading&&state.slotsLoadedFor!==`${state.date}:${state.type}`)loadSlots()}
function input(k,label,placeholder,required=false,type='text'){return `<div class="field"><label for="f-${k}">${label} ${required?'<span class="required">*</span>':''}</label><input id="f-${k}" type="${type}" placeholder="${placeholder}" value="${esc(state.form[k])}" ${required?'required':''}></div>`}
function renderDetails(){app.innerHTML=`<div class="content"><div class="kicker">03 · A little context</div><h2 class="title">Help me arrive prepared.</h2><p class="sub">Only the essentials are required. The extra context is optional, but it makes the conversation more useful.</p><div class="form"><div class="row">${input('name','Your name','Kevin Okacha',true)}${input('email','Email','you@company.com',true,'email')}</div><div class="row">${input('company','Company','Company or project')}${input('website','Website','https://…')}</div><div class="row">${input('phone','Phone','Optional')}${input('goals','Primary goal','What would make this call valuable?')}</div><div class="field"><label for="f-projectDetails">Project / situation</label><textarea id="f-projectDetails" placeholder="A few lines of context, current setup, audience, constraints…">${esc(state.form.projectDetails)}</textarea></div><div class="field"><label for="f-notes">Anything else</label><textarea id="f-notes" placeholder="Links, questions, or anything I should know before we meet.">${esc(state.form.notes)}</textarea></div></div>${state.error?`<div class="error">${esc(state.error)}</div>`:''}<div class="actions"><button class="btn ghost" id="back-details">← Back</button><button class="btn primary" id="next-details">Review booking →</button></div></div>`;document.querySelectorAll('.form input,.form textarea').forEach(el=>el.addEventListener('input',()=>{state.form[el.id.replace('f-','')]=el.value}));document.getElementById('back-details').onclick=()=>setStep(2);document.getElementById('next-details').onclick=()=>{saveForm();if(!state.form.name||!state.form.email||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(state.form.email)){state.error='Please add your name and a valid email address.';render();return}setStep(4)}}
function renderConfirm(){const t=TYPES[state.type];app.innerHTML=`<div class="content"><div class="kicker">04 · Review & confirm</div><h2 class="title">Everything look right?</h2><p class="sub">Confirm once and the system will create the Calendar event and a real Google Meet conference.</p><div class="summary"><div class="summary-top"><div><h3>${t.label}</h3><div class="when">${fmt(state.slot,{dateStyle:'full',timeStyle:'short'})}<br>${t.duration} minutes · East Africa Time</div></div><span class="pill">Google Meet</span></div></div><div class="notice"><strong>${esc(state.form.name)}</strong> · ${esc(state.form.email)}<br>${state.form.company?esc(state.form.company)+' · ':''}${state.form.goals?esc(state.form.goals):'No goal added'}</div>${state.error?`<div class="error">${esc(state.error)}</div>`:''}<div class="actions"><button class="btn ghost" id="back-confirm">← Edit details</button><button class="btn primary" id="confirm">Confirm booking</button></div><p class="confirm-copy">By confirming, a Google Calendar event will be created and the invite will be sent to the email above. The meeting link is generated by Google, not by the browser.</p></div>`;document.getElementById('back-confirm').onclick=()=>setStep(3);document.getElementById('confirm').onclick=confirmBooking}
async function confirmBooking(){saveForm();const btn=document.getElementById('confirm');btn.disabled=true;btn.textContent='Creating your meeting…';state.error='';try{const r=await fetch('/api/bookings/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({meetingType:state.type,startAt:state.slot,...state.form})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Booking failed');state.booking=j.booking;render()}catch(e){state.error=e.message;render()}}
function renderSuccess(){const b=state.booking;app.innerHTML=`<div class="success"><div class="success-icon">✓</div><div class="kicker">Booked</div><h2>You’re on the calendar.</h2><p>${esc(b.name)}, your ${esc(b.meetingType)} is confirmed for <strong>${fmt(b.startAt,{dateStyle:'full',timeStyle:'short'})}</strong>.</p><a class="meet" href="${esc(b.meetUrl)}" target="_blank" rel="noopener">Join Google Meet ↗</a><div class="ref">REFERENCE · ${esc(b.reference)}</div><p>Google has also sent the calendar invitation to <strong>${esc(b.email)}</strong>. Keep the reference above if you need to reschedule or cancel later.</p><button class="btn ghost" id="again">Book another session</button></div>`;document.getElementById('again').onclick=()=>{Object.assign(state,{step:1,type:null,date:null,slot:null,slotsLoadedFor:null,booking:null,error:''});state.form={name:'',email:'',company:'',website:'',phone:'',goals:'',projectDetails:'',notes:''};render()}}
async function checkConnection(){try{const r=await fetch('/api/auth/google/status');const j=await r.json();const el=document.getElementById('connection-status');if(j.connected){document.querySelector('.status').classList.add('connected');el.textContent='Google Calendar connected'}else{el.innerHTML='<a class="connect" href="/api/auth/google/start">Connect Google Calendar</a>'}}catch{document.getElementById('connection-status').textContent='Calendar connection unavailable'}}
const params=new URLSearchParams(location.search);if(params.get('google')==='connected'){history.replaceState({},'',location.pathname)}
render();checkConnection();
